import type mysql from 'mysql2/promise'
import { mysqlPool } from '#infrastructure/database/mysqlPool.js'
import { AppError } from '#domain/errors/appError.js'
import type { ReservationRepository, ReservationDetail } from '#domain/interfaces/repositories/reservation-repository.js'
import type { BookingType, Reservation, SeatLayout, SeatPosition, TicketType } from '#domain/entities/reservation.js'

export class MysqlReservationRepository implements ReservationRepository {
  async findPublicSchedule(id:number) { const [r]=await mysqlPool.execute<mysql.RowDataPacket[]>(`SELECT sch.screen_id, item.title, sch.starts_at, sch.ends_at, sc.name screen_name FROM schedules sch JOIN screenings item ON item.id=sch.screening_id JOIN screens sc ON sc.id=sch.screen_id WHERE sch.id=? AND sch.is_public=1`,[id]); return r[0] ? {screenId:Number(r[0].screen_id),title:String(r[0].title),startsAt:r[0].starts_at,endsAt:r[0].ends_at,screenName:String(r[0].screen_name)} : null }
  async findLayout(screenId:number):Promise<SeatLayout|null>{const [r]=await mysqlPool.execute<mysql.RowDataPacket[]>('SELECT id,layout_version,background_image_url,aspect_ratio_width,aspect_ratio_height FROM screen_seat_layouts WHERE screen_id=?',[screenId]);return r[0]?{id:Number(r[0].id),version:Number(r[0].layout_version),backgroundImageUrl:r[0].background_image_url as string|null,aspectRatioWidth:Number(r[0].aspect_ratio_width),aspectRatioHeight:Number(r[0].aspect_ratio_height)}:null}
  async findSeats(scheduleId:number,screenId:number):Promise<SeatPosition[]>{const [r]=await mysqlPool.execute<mysql.RowDataPacket[]>(`SELECT s.id seat_id,s.row_label,s.col_no,s.position_top_pct,s.position_left_pct,s.seat_width_pct,s.seat_height_pct,s.hit_radius_pct,CASE WHEN r.status='confirmed' THEN 'reserved' WHEN r.status='pending' THEN 'held' ELSE 'available' END status FROM seats s LEFT JOIN reservation_seats rs ON rs.schedule_id=? AND rs.seat_id=s.id LEFT JOIN reservations r ON r.id=rs.reservation_id AND (r.status='confirmed' OR (r.status='pending' AND r.expires_at>CURRENT_TIMESTAMP(3))) WHERE s.screen_id=? ORDER BY s.row_label,s.col_no`,[scheduleId,screenId]);return r.map(x=>({seatId:Number(x.seat_id),row:String(x.row_label),col:Number(x.col_no),topPct:Number(x.position_top_pct),leftPct:Number(x.position_left_pct),widthPct:Number(x.seat_width_pct),heightPct:Number(x.seat_height_pct),hitRadiusPct:x.hit_radius_pct==null?null:Number(x.hit_radius_pct),status:x.status as SeatPosition['status']}))}
  async findSeatsInScreen(ids:number[],screenId:number){const p=ids.map(()=>'?').join(',');const[r]=await mysqlPool.execute<mysql.RowDataPacket[]>(`SELECT id,row_label,col_no FROM seats WHERE id IN (${p}) AND screen_id=?`,[...ids,screenId]);return new Map(r.map(x=>[Number(x.id),{row:String(x.row_label),col:Number(x.col_no)}]))}
  async reservationCodeExists(code:string){const[r]=await mysqlPool.execute<mysql.RowDataPacket[]>('SELECT id FROM reservations WHERE reservation_code=?',[code]);return r.length>0}
  async findDetail(code:string):Promise<ReservationDetail|null>{const[r]=await mysqlPool.execute<mysql.RowDataPacket[]>(`SELECT r.id,r.reservation_code,r.status,r.booking_type,r.customer_email,r.total_price,item.title screening_title,item.type screening_type,(SELECT file_name FROM images WHERE entity_type='screening' AND entity_id=item.id ORDER BY display_order LIMIT 1) thumbnail_url,sch.starts_at,sch.ends_at,sc.name screen_name FROM reservations r JOIN schedules sch ON sch.id=r.schedule_id JOIN screenings item ON item.id=sch.screening_id JOIN screens sc ON sc.id=sch.screen_id WHERE r.reservation_code=?`,[code]);if(!r[0])return null;const[s]=await mysqlPool.execute<mysql.RowDataPacket[]>(`SELECT s.row_label,s.col_no,rs.ticket_type,rs.price FROM reservation_seats rs JOIN seats s ON s.id=rs.seat_id WHERE rs.reservation_id=? ORDER BY s.row_label,s.col_no`,[r[0].id]);const x=r[0];return{reservationCode:String(x.reservation_code),status:String(x.status),bookingType:x.booking_type as BookingType,customerEmail:String(x.customer_email),totalPrice:Number(x.total_price),screeningTitle:String(x.screening_title),screeningType:x.screening_type as ReservationDetail['screeningType'],thumbnailUrl:x.thumbnail_url as string|null,startsAt:x.starts_at,endsAt:x.ends_at,screenName:String(x.screen_name),seats:s.map(y=>({row:String(y.row_label),col:Number(y.col_no),ticketType:String(y.ticket_type),price:Number(y.price)}))}}
  async findForCancel(code:string):Promise<Reservation|null>{const[r]=await mysqlPool.execute<mysql.RowDataPacket[]>(`SELECT r.id,r.reservation_code,r.member_id,r.booking_type,r.customer_email,r.status,sch.starts_at FROM reservations r JOIN schedules sch ON sch.id=r.schedule_id WHERE r.reservation_code=?`,[code]);const x=r[0];return x?{id:Number(x.id),reservationCode:String(x.reservation_code),memberId:x.member_id==null?null:Number(x.member_id),bookingType:x.booking_type as BookingType,customerEmail:String(x.customer_email),status:x.status as Reservation['status'],startsAt:x.starts_at}:null}
  async cancel(id:number){await mysqlPool.execute('UPDATE reservations SET status=? WHERE id=?',['cancelled',id])}
  async hold(scheduleId:number,ids:number[],expiresAt:Date,code:string){const p=ids.map(()=>'?').join(',');const c=await mysqlPool.getConnection();await c.beginTransaction();try{await c.execute(`DELETE rs FROM reservation_seats rs JOIN reservations r ON r.id=rs.reservation_id WHERE rs.schedule_id=? AND rs.seat_id IN (${p}) AND r.status='pending' AND r.expires_at<=CURRENT_TIMESTAMP(3)`,[scheduleId,...ids]);const[x]=await c.execute<mysql.RowDataPacket[]>(`SELECT rs.seat_id FROM reservation_seats rs JOIN reservations r ON r.id=rs.reservation_id WHERE rs.schedule_id=? AND rs.seat_id IN (${p}) AND (r.status='confirmed' OR (r.status='pending' AND r.expires_at>CURRENT_TIMESTAMP(3))) FOR UPDATE`,[scheduleId,...ids]);if(x.length)throw new AppError('SEAT_ALREADY_RESERVED','One or more seats are already reserved or held');const[z]=await c.execute<mysql.ResultSetHeader>(`INSERT INTO reservations(reservation_code,schedule_id,status,expires_at,total_price) VALUES (?,?,'pending',?,0)`,[code,scheduleId,expiresAt]);for(const id of ids)await c.execute(`INSERT INTO reservation_seats(reservation_id,schedule_id,seat_id,ticket_type,price) VALUES (?,?,?,'general',0)`,[z.insertId,scheduleId,id]);await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
  async finalize(input:{reservationCode?:string;scheduleId:number;memberId:number|null;bookingType:BookingType;customerEmail:string;tickets:{seatId:number;ticketType:TicketType}[];totalPrice:number;generatedCode:string}){const ids=input.tickets.map(x=>x.seatId),p=ids.map(()=>'?').join(',');const c=await mysqlPool.getConnection();await c.beginTransaction();try{const[x]=await c.execute<mysql.RowDataPacket[]>(`SELECT rs.seat_id FROM reservation_seats rs JOIN reservations r ON r.id=rs.reservation_id WHERE rs.schedule_id=? AND rs.seat_id IN (${p}) AND (r.status='confirmed' OR (r.status='pending' AND r.expires_at>CURRENT_TIMESTAMP(3))) ${input.reservationCode?'AND r.reservation_code<>?':''} FOR UPDATE`,input.reservationCode?[input.scheduleId,...ids,input.reservationCode]:[input.scheduleId,...ids]);if(x.length)throw new AppError('SEAT_ALREADY_RESERVED','One or more seats are already reserved or held');let id:number, reservationCode=input.reservationCode??input.generatedCode;if(input.reservationCode){const[r]=await c.execute<mysql.RowDataPacket[]>(`SELECT id FROM reservations WHERE reservation_code=? AND status='pending' AND schedule_id=? FOR UPDATE`,[input.reservationCode,input.scheduleId]);if(!r[0])throw new AppError('NOT_FOUND','Valid tentative reservation not found');id=Number(r[0].id);await c.execute(`UPDATE reservations SET status='confirmed',expires_at=NULL,member_id=?,booking_type=?,customer_name=NULL,customer_email=?,total_price=? WHERE id=?`,[input.memberId,input.bookingType,input.customerEmail,input.totalPrice,id]);await c.execute('DELETE FROM reservation_seats WHERE reservation_id=?',[id])}else{const[r]=await c.execute<mysql.ResultSetHeader>(`INSERT INTO reservations(reservation_code,schedule_id,member_id,booking_type,customer_name,customer_email,total_price) VALUES (?,?,?,?,NULL,?,?)`,[reservationCode,input.scheduleId,input.memberId,input.bookingType,input.customerEmail,input.totalPrice]);id=r.insertId}for(const t of input.tickets)await c.execute(`INSERT INTO reservation_seats(reservation_id,schedule_id,seat_id,ticket_type,price) VALUES (?,?,?,?,?)`,[id,input.scheduleId,t.seatId,t.ticketType,{general:1800,university:1600,highschool:1400,child:1000}[t.ticketType]]);await c.commit();return{reservationId:id,reservationCode}}catch(e){await c.rollback();throw e}finally{c.release()}}
}
